-- ============================================================
-- NEXUS · Datos semilla de catálogos (PostgreSQL / Supabase)
-- Se genera a partir de la jerarquía país→departamento/estado→
-- ciudad y de la lista de categorías que estaban incrustadas
-- como listas fijas dentro del prototipo HTML (constante GEO y
-- el <select id="f_cat">), más los 9 estados de proyecto ya
-- definidos en el prototipo (agrupados en las mismas 3 fases
-- que ya usaba el HTML, más 'No ejecutado' que viene del Excel).
-- Ejecutar DESPUÉS de nexus_schema_v2.sql.
-- ============================================================

-- ---------- PAÍSES ----------
INSERT INTO paises (nombre, etiqueta_region) VALUES
  ('Colombia', 'Departamento'),
  ('México', 'Estado'),
  ('Estados Unidos', 'Estado');

-- ---------- DEPARTAMENTOS / ESTADOS ----------
INSERT INTO regiones (pais_id, nombre)
SELECT p.id, v.nombre FROM (VALUES
  ('Colombia', 'Amazonas'),
  ('Colombia', 'Antioquia'),
  ('Colombia', 'Arauca'),
  ('Colombia', 'Atlántico'),
  ('Colombia', 'Bogotá D.C.'),
  ('Colombia', 'Bolívar'),
  ('Colombia', 'Boyacá'),
  ('Colombia', 'Caldas'),
  ('Colombia', 'Caquetá'),
  ('Colombia', 'Casanare'),
  ('Colombia', 'Cauca'),
  ('Colombia', 'César'),
  ('Colombia', 'Chocó'),
  ('Colombia', 'Córdoba'),
  ('Colombia', 'Cundinamarca'),
  ('Colombia', 'Guainía'),
  ('Colombia', 'Guaviare'),
  ('Colombia', 'Huila'),
  ('Colombia', 'La Guajira'),
  ('Colombia', 'Magdalena'),
  ('Colombia', 'Meta'),
  ('Colombia', 'Nariño'),
  ('Colombia', 'Norte de Santander'),
  ('Colombia', 'Putumayo'),
  ('Colombia', 'Quindío'),
  ('Colombia', 'Risaralda'),
  ('Colombia', 'San Andrés y Providencia'),
  ('Colombia', 'Santander'),
  ('Colombia', 'Sucre'),
  ('Colombia', 'Tolima'),
  ('Colombia', 'Valle del Cauca'),
  ('Colombia', 'Vaupés'),
  ('Colombia', 'Vichada'),
  ('México', 'Aguascalientes'),
  ('México', 'Baja California'),
  ('México', 'Baja California Sur'),
  ('México', 'Campeche'),
  ('México', 'Chiapas'),
  ('México', 'Chihuahua'),
  ('México', 'Ciudad de México'),
  ('México', 'Coahuila'),
  ('México', 'Colima'),
  ('México', 'Durango'),
  ('México', 'Guanajuato'),
  ('México', 'Guerrero'),
  ('México', 'Hidalgo'),
  ('México', 'Jalisco'),
  ('México', 'Estado de México'),
  ('México', 'Michoacán'),
  ('México', 'Morelos'),
  ('México', 'Nayarit'),
  ('México', 'Nuevo León'),
  ('México', 'Oaxaca'),
  ('México', 'Puebla'),
  ('México', 'Querétaro'),
  ('México', 'Quintana Roo'),
  ('México', 'San Luis Potosí'),
  ('México', 'Sinaloa'),
  ('México', 'Sonora'),
  ('México', 'Tabasco'),
  ('México', 'Tamaulipas'),
  ('México', 'Tlaxcala'),
  ('México', 'Veracruz'),
  ('México', 'Yucatán'),
  ('México', 'Zacatecas'),
  ('Estados Unidos', 'Alabama'),
  ('Estados Unidos', 'Alaska'),
  ('Estados Unidos', 'Arizona'),
  ('Estados Unidos', 'Arkansas'),
  ('Estados Unidos', 'California'),
  ('Estados Unidos', 'Colorado'),
  ('Estados Unidos', 'Connecticut'),
  ('Estados Unidos', 'Delaware'),
  ('Estados Unidos', 'Florida'),
  ('Estados Unidos', 'Georgia'),
  ('Estados Unidos', 'Hawaii'),
  ('Estados Unidos', 'Idaho'),
  ('Estados Unidos', 'Illinois'),
  ('Estados Unidos', 'Indiana'),
  ('Estados Unidos', 'Iowa'),
  ('Estados Unidos', 'Kansas'),
  ('Estados Unidos', 'Kentucky'),
  ('Estados Unidos', 'Louisiana'),
  ('Estados Unidos', 'Maine'),
  ('Estados Unidos', 'Maryland'),
  ('Estados Unidos', 'Massachusetts'),
  ('Estados Unidos', 'Michigan'),
  ('Estados Unidos', 'Minnesota'),
  ('Estados Unidos', 'Mississippi'),
  ('Estados Unidos', 'Missouri'),
  ('Estados Unidos', 'Montana'),
  ('Estados Unidos', 'Nebraska'),
  ('Estados Unidos', 'Nevada'),
  ('Estados Unidos', 'New Hampshire'),
  ('Estados Unidos', 'New Jersey'),
  ('Estados Unidos', 'New Mexico'),
  ('Estados Unidos', 'New York'),
  ('Estados Unidos', 'North Carolina'),
  ('Estados Unidos', 'North Dakota'),
  ('Estados Unidos', 'Ohio'),
  ('Estados Unidos', 'Oklahoma'),
  ('Estados Unidos', 'Oregon'),
  ('Estados Unidos', 'Pennsylvania'),
  ('Estados Unidos', 'Rhode Island'),
  ('Estados Unidos', 'South Carolina'),
  ('Estados Unidos', 'South Dakota'),
  ('Estados Unidos', 'Tennessee'),
  ('Estados Unidos', 'Texas'),
  ('Estados Unidos', 'Utah'),
  ('Estados Unidos', 'Vermont'),
  ('Estados Unidos', 'Virginia'),
  ('Estados Unidos', 'Washington'),
  ('Estados Unidos', 'West Virginia'),
  ('Estados Unidos', 'Wisconsin'),
  ('Estados Unidos', 'Wyoming')
) AS v(pais, nombre)
JOIN paises p ON p.nombre = v.pais;

-- ---------- CIUDADES ----------
INSERT INTO ciudades (region_id, nombre)
SELECT r.id, v.ciudad FROM (VALUES
  ('Colombia', 'Amazonas', 'Leticia'),
  ('Colombia', 'Amazonas', 'Puerto Nariño'),
  ('Colombia', 'Antioquia', 'Medellín'),
  ('Colombia', 'Antioquia', 'Bello'),
  ('Colombia', 'Antioquia', 'Itagüí'),
  ('Colombia', 'Antioquia', 'Envigado'),
  ('Colombia', 'Antioquia', 'Apartadó'),
  ('Colombia', 'Antioquia', 'Turbo'),
  ('Colombia', 'Antioquia', 'Rionegro'),
  ('Colombia', 'Antioquia', 'Sabaneta'),
  ('Colombia', 'Antioquia', 'La Estrella'),
  ('Colombia', 'Antioquia', 'Copacabana'),
  ('Colombia', 'Arauca', 'Arauca'),
  ('Colombia', 'Arauca', 'Saravena'),
  ('Colombia', 'Arauca', 'Tame'),
  ('Colombia', 'Atlántico', 'Barranquilla'),
  ('Colombia', 'Atlántico', 'Soledad'),
  ('Colombia', 'Atlántico', 'Malambo'),
  ('Colombia', 'Atlántico', 'Sabanalarga'),
  ('Colombia', 'Atlántico', 'Santo Tomás'),
  ('Colombia', 'Bogotá D.C.', 'Bogotá'),
  ('Colombia', 'Bolívar', 'Cartagena'),
  ('Colombia', 'Bolívar', 'Magangué'),
  ('Colombia', 'Bolívar', 'El Carmen de Bolívar'),
  ('Colombia', 'Bolívar', 'Turbaco'),
  ('Colombia', 'Boyacá', 'Tunja'),
  ('Colombia', 'Boyacá', 'Duitama'),
  ('Colombia', 'Boyacá', 'Sogamoso'),
  ('Colombia', 'Boyacá', 'Chiquinquirá'),
  ('Colombia', 'Caldas', 'Manizales'),
  ('Colombia', 'Caldas', 'Villamaría'),
  ('Colombia', 'Caldas', 'La Dorada'),
  ('Colombia', 'Caldas', 'Chinchiná'),
  ('Colombia', 'Caquetá', 'Florencia'),
  ('Colombia', 'Caquetá', 'San Vicente del Caguán'),
  ('Colombia', 'Casanare', 'Yopal'),
  ('Colombia', 'Casanare', 'Aguazul'),
  ('Colombia', 'Casanare', 'Paz de Ariporo'),
  ('Colombia', 'Cauca', 'Popayán'),
  ('Colombia', 'Cauca', 'Santander de Quilichao'),
  ('Colombia', 'Cauca', 'Puerto Tejada'),
  ('Colombia', 'César', 'Valledupar'),
  ('Colombia', 'César', 'Aguachica'),
  ('Colombia', 'César', 'Bosconia'),
  ('Colombia', 'Chocó', 'Quibdó'),
  ('Colombia', 'Chocó', 'Istmina'),
  ('Colombia', 'Chocó', 'Tadó'),
  ('Colombia', 'Córdoba', 'Montería'),
  ('Colombia', 'Córdoba', 'Cereté'),
  ('Colombia', 'Córdoba', 'Lorica'),
  ('Colombia', 'Córdoba', 'Sahagún'),
  ('Colombia', 'Cundinamarca', 'Soacha'),
  ('Colombia', 'Cundinamarca', 'Fusagasugá'),
  ('Colombia', 'Cundinamarca', 'Facatativá'),
  ('Colombia', 'Cundinamarca', 'Zipaquirá'),
  ('Colombia', 'Cundinamarca', 'Girardot'),
  ('Colombia', 'Cundinamarca', 'Chía'),
  ('Colombia', 'Cundinamarca', 'Cajicá'),
  ('Colombia', 'Guainía', 'Inírida'),
  ('Colombia', 'Guaviare', 'San José del Guaviare'),
  ('Colombia', 'Huila', 'Neiva'),
  ('Colombia', 'Huila', 'Pitalito'),
  ('Colombia', 'Huila', 'Garzón'),
  ('Colombia', 'Huila', 'La Plata'),
  ('Colombia', 'La Guajira', 'Riohacha'),
  ('Colombia', 'La Guajira', 'Maicao'),
  ('Colombia', 'La Guajira', 'Uribia'),
  ('Colombia', 'Magdalena', 'Santa Marta'),
  ('Colombia', 'Magdalena', 'Ciénaga'),
  ('Colombia', 'Magdalena', 'Fundación'),
  ('Colombia', 'Meta', 'Villavicencio'),
  ('Colombia', 'Meta', 'Acacías'),
  ('Colombia', 'Meta', 'Granada'),
  ('Colombia', 'Nariño', 'Pasto'),
  ('Colombia', 'Nariño', 'Tumaco'),
  ('Colombia', 'Nariño', 'Ipiales'),
  ('Colombia', 'Nariño', 'Túquerres'),
  ('Colombia', 'Norte de Santander', 'Cúcuta'),
  ('Colombia', 'Norte de Santander', 'Ocaña'),
  ('Colombia', 'Norte de Santander', 'Pamplona'),
  ('Colombia', 'Norte de Santander', 'Villa del Rosario'),
  ('Colombia', 'Putumayo', 'Mocoa'),
  ('Colombia', 'Putumayo', 'Puerto Asís'),
  ('Colombia', 'Quindío', 'Armenia'),
  ('Colombia', 'Quindío', 'Calarcá'),
  ('Colombia', 'Quindío', 'Montenegro'),
  ('Colombia', 'Risaralda', 'Pereira'),
  ('Colombia', 'Risaralda', 'Dosquebradas'),
  ('Colombia', 'Risaralda', 'Santa Rosa de Cabal'),
  ('Colombia', 'San Andrés y Providencia', 'San Andrés'),
  ('Colombia', 'San Andrés y Providencia', 'Providencia'),
  ('Colombia', 'Santander', 'Bucaramanga'),
  ('Colombia', 'Santander', 'Floridablanca'),
  ('Colombia', 'Santander', 'Girón'),
  ('Colombia', 'Santander', 'Piedecuesta'),
  ('Colombia', 'Santander', 'Barrancabermeja'),
  ('Colombia', 'Sucre', 'Sincelejo'),
  ('Colombia', 'Sucre', 'Corozal'),
  ('Colombia', 'Sucre', 'Sampués'),
  ('Colombia', 'Tolima', 'Ibagué'),
  ('Colombia', 'Tolima', 'Espinal'),
  ('Colombia', 'Tolima', 'Melgar'),
  ('Colombia', 'Tolima', 'Chaparral'),
  ('Colombia', 'Valle del Cauca', 'Cali'),
  ('Colombia', 'Valle del Cauca', 'Buenaventura'),
  ('Colombia', 'Valle del Cauca', 'Palmira'),
  ('Colombia', 'Valle del Cauca', 'Tuluá'),
  ('Colombia', 'Valle del Cauca', 'Cartago'),
  ('Colombia', 'Valle del Cauca', 'Buga'),
  ('Colombia', 'Valle del Cauca', 'Yumbo'),
  ('Colombia', 'Vaupés', 'Mitú'),
  ('Colombia', 'Vichada', 'Puerto Carreño'),
  ('México', 'Aguascalientes', 'Aguascalientes'),
  ('México', 'Aguascalientes', 'Jesús María'),
  ('México', 'Aguascalientes', 'Calvillo'),
  ('México', 'Baja California', 'Tijuana'),
  ('México', 'Baja California', 'Mexicali'),
  ('México', 'Baja California', 'Ensenada'),
  ('México', 'Baja California', 'Rosarito'),
  ('México', 'Baja California Sur', 'La Paz'),
  ('México', 'Baja California Sur', 'Los Cabos'),
  ('México', 'Baja California Sur', 'Loreto'),
  ('México', 'Campeche', 'Campeche'),
  ('México', 'Campeche', 'Ciudad del Carmen'),
  ('México', 'Chiapas', 'Tuxtla Gutiérrez'),
  ('México', 'Chiapas', 'San Cristóbal de las Casas'),
  ('México', 'Chiapas', 'Tapachula'),
  ('México', 'Chihuahua', 'Chihuahua'),
  ('México', 'Chihuahua', 'Ciudad Juárez'),
  ('México', 'Chihuahua', 'Delicias'),
  ('México', 'Chihuahua', 'Cuauhtémoc'),
  ('México', 'Ciudad de México', 'Benito Juárez'),
  ('México', 'Ciudad de México', 'Miguel Hidalgo'),
  ('México', 'Ciudad de México', 'Coyoacán'),
  ('México', 'Ciudad de México', 'Cuauhtémoc'),
  ('México', 'Ciudad de México', 'Álvaro Obregón'),
  ('México', 'Ciudad de México', 'Tlalpan'),
  ('México', 'Ciudad de México', 'Iztapalapa'),
  ('México', 'Coahuila', 'Saltillo'),
  ('México', 'Coahuila', 'Torreón'),
  ('México', 'Coahuila', 'Monclova'),
  ('México', 'Coahuila', 'Piedras Negras'),
  ('México', 'Colima', 'Colima'),
  ('México', 'Colima', 'Manzanillo'),
  ('México', 'Colima', 'Tecomán'),
  ('México', 'Durango', 'Durango'),
  ('México', 'Durango', 'Gómez Palacio'),
  ('México', 'Durango', 'Lerdo'),
  ('México', 'Guanajuato', 'León'),
  ('México', 'Guanajuato', 'Irapuato'),
  ('México', 'Guanajuato', 'Celaya'),
  ('México', 'Guanajuato', 'Salamanca'),
  ('México', 'Guanajuato', 'Guanajuato'),
  ('México', 'Guerrero', 'Acapulco'),
  ('México', 'Guerrero', 'Chilpancingo'),
  ('México', 'Guerrero', 'Iguala'),
  ('México', 'Guerrero', 'Zihuatanejo'),
  ('México', 'Hidalgo', 'Pachuca'),
  ('México', 'Hidalgo', 'Tulancingo'),
  ('México', 'Hidalgo', 'Tula de Allende'),
  ('México', 'Jalisco', 'Guadalajara'),
  ('México', 'Jalisco', 'Zapopan'),
  ('México', 'Jalisco', 'Tlaquepaque'),
  ('México', 'Jalisco', 'Tonalá'),
  ('México', 'Jalisco', 'Puerto Vallarta'),
  ('México', 'Estado de México', 'Ecatepec'),
  ('México', 'Estado de México', 'Naucalpan'),
  ('México', 'Estado de México', 'Tlalnepantla'),
  ('México', 'Estado de México', 'Toluca'),
  ('México', 'Estado de México', 'Neza'),
  ('México', 'Estado de México', 'Chimalhuacán'),
  ('México', 'Michoacán', 'Morelia'),
  ('México', 'Michoacán', 'Uruapan'),
  ('México', 'Michoacán', 'Apatzingán'),
  ('México', 'Michoacán', 'Zamora'),
  ('México', 'Morelos', 'Cuernavaca'),
  ('México', 'Morelos', 'Jiutepec'),
  ('México', 'Morelos', 'Cuautla'),
  ('México', 'Nayarit', 'Tepic'),
  ('México', 'Nayarit', 'Bahía de Banderas'),
  ('México', 'Nayarit', 'Xalisco'),
  ('México', 'Nuevo León', 'Monterrey'),
  ('México', 'Nuevo León', 'San Nicolás'),
  ('México', 'Nuevo León', 'Guadalupe'),
  ('México', 'Nuevo León', 'Apodaca'),
  ('México', 'Nuevo León', 'San Pedro Garza García'),
  ('México', 'Nuevo León', 'Santa Catarina'),
  ('México', 'Oaxaca', 'Oaxaca de Juárez'),
  ('México', 'Oaxaca', 'Tuxtepec'),
  ('México', 'Oaxaca', 'Juchitán'),
  ('México', 'Oaxaca', 'Puerto Escondido'),
  ('México', 'Puebla', 'Puebla'),
  ('México', 'Puebla', 'Tehuacán'),
  ('México', 'Puebla', 'San Andrés Cholula'),
  ('México', 'Puebla', 'Atlixco'),
  ('México', 'Querétaro', 'Querétaro'),
  ('México', 'Querétaro', 'San Juan del Río'),
  ('México', 'Querétaro', 'Corregidora'),
  ('México', 'Quintana Roo', 'Cancún'),
  ('México', 'Quintana Roo', 'Playa del Carmen'),
  ('México', 'Quintana Roo', 'Cozumel'),
  ('México', 'Quintana Roo', 'Tulum'),
  ('México', 'Quintana Roo', 'Chetumal'),
  ('México', 'San Luis Potosí', 'San Luis Potosí'),
  ('México', 'San Luis Potosí', 'Ciudad Valles'),
  ('México', 'San Luis Potosí', 'Matehuala'),
  ('México', 'Sinaloa', 'Culiacán'),
  ('México', 'Sinaloa', 'Mazatlán'),
  ('México', 'Sinaloa', 'Los Mochis'),
  ('México', 'Sinaloa', 'Guasave'),
  ('México', 'Sonora', 'Hermosillo'),
  ('México', 'Sonora', 'Ciudad Obregón'),
  ('México', 'Sonora', 'Nogales'),
  ('México', 'Sonora', 'Guaymas'),
  ('México', 'Tabasco', 'Villahermosa'),
  ('México', 'Tabasco', 'Cárdenas'),
  ('México', 'Tabasco', 'Comalcalco'),
  ('México', 'Tamaulipas', 'Reynosa'),
  ('México', 'Tamaulipas', 'Matamoros'),
  ('México', 'Tamaulipas', 'Nuevo Laredo'),
  ('México', 'Tamaulipas', 'Tampico'),
  ('México', 'Tamaulipas', 'Victoria'),
  ('México', 'Tlaxcala', 'Tlaxcala'),
  ('México', 'Tlaxcala', 'Apizaco'),
  ('México', 'Tlaxcala', 'Huamantla'),
  ('México', 'Veracruz', 'Veracruz'),
  ('México', 'Veracruz', 'Xalapa'),
  ('México', 'Veracruz', 'Coatzacoalcos'),
  ('México', 'Veracruz', 'Córdoba'),
  ('México', 'Veracruz', 'Orizaba'),
  ('México', 'Yucatán', 'Mérida'),
  ('México', 'Yucatán', 'Valladolid'),
  ('México', 'Yucatán', 'Tizimín'),
  ('México', 'Zacatecas', 'Zacatecas'),
  ('México', 'Zacatecas', 'Fresnillo'),
  ('México', 'Zacatecas', 'Guadalupe'),
  ('Estados Unidos', 'Alabama', 'Birmingham'),
  ('Estados Unidos', 'Alabama', 'Montgomery'),
  ('Estados Unidos', 'Alabama', 'Huntsville'),
  ('Estados Unidos', 'Alaska', 'Anchorage'),
  ('Estados Unidos', 'Alaska', 'Juneau'),
  ('Estados Unidos', 'Alaska', 'Fairbanks'),
  ('Estados Unidos', 'Arizona', 'Phoenix'),
  ('Estados Unidos', 'Arizona', 'Tucson'),
  ('Estados Unidos', 'Arizona', 'Scottsdale'),
  ('Estados Unidos', 'Arizona', 'Tempe'),
  ('Estados Unidos', 'Arkansas', 'Little Rock'),
  ('Estados Unidos', 'Arkansas', 'Fort Smith'),
  ('Estados Unidos', 'Arkansas', 'Fayetteville'),
  ('Estados Unidos', 'California', 'Los Angeles'),
  ('Estados Unidos', 'California', 'San Francisco'),
  ('Estados Unidos', 'California', 'San Diego'),
  ('Estados Unidos', 'California', 'Sacramento'),
  ('Estados Unidos', 'California', 'San Jose'),
  ('Estados Unidos', 'California', 'Fresno'),
  ('Estados Unidos', 'California', 'Oakland'),
  ('Estados Unidos', 'Colorado', 'Denver'),
  ('Estados Unidos', 'Colorado', 'Colorado Springs'),
  ('Estados Unidos', 'Colorado', 'Aurora'),
  ('Estados Unidos', 'Colorado', 'Boulder'),
  ('Estados Unidos', 'Connecticut', 'Hartford'),
  ('Estados Unidos', 'Connecticut', 'New Haven'),
  ('Estados Unidos', 'Connecticut', 'Bridgeport'),
  ('Estados Unidos', 'Delaware', 'Wilmington'),
  ('Estados Unidos', 'Delaware', 'Dover'),
  ('Estados Unidos', 'Florida', 'Miami'),
  ('Estados Unidos', 'Florida', 'Orlando'),
  ('Estados Unidos', 'Florida', 'Tampa'),
  ('Estados Unidos', 'Florida', 'Jacksonville'),
  ('Estados Unidos', 'Florida', 'Fort Lauderdale'),
  ('Estados Unidos', 'Florida', 'Hialeah'),
  ('Estados Unidos', 'Georgia', 'Atlanta'),
  ('Estados Unidos', 'Georgia', 'Augusta'),
  ('Estados Unidos', 'Georgia', 'Savannah'),
  ('Estados Unidos', 'Georgia', 'Columbus'),
  ('Estados Unidos', 'Hawaii', 'Honolulu'),
  ('Estados Unidos', 'Hawaii', 'Pearl City'),
  ('Estados Unidos', 'Hawaii', 'Hilo'),
  ('Estados Unidos', 'Idaho', 'Boise'),
  ('Estados Unidos', 'Idaho', 'Meridian'),
  ('Estados Unidos', 'Idaho', 'Nampa'),
  ('Estados Unidos', 'Illinois', 'Chicago'),
  ('Estados Unidos', 'Illinois', 'Aurora'),
  ('Estados Unidos', 'Illinois', 'Rockford'),
  ('Estados Unidos', 'Illinois', 'Naperville'),
  ('Estados Unidos', 'Indiana', 'Indianapolis'),
  ('Estados Unidos', 'Indiana', 'Fort Wayne'),
  ('Estados Unidos', 'Indiana', 'Evansville'),
  ('Estados Unidos', 'Iowa', 'Des Moines'),
  ('Estados Unidos', 'Iowa', 'Cedar Rapids'),
  ('Estados Unidos', 'Iowa', 'Davenport'),
  ('Estados Unidos', 'Kansas', 'Wichita'),
  ('Estados Unidos', 'Kansas', 'Overland Park'),
  ('Estados Unidos', 'Kansas', 'Kansas City'),
  ('Estados Unidos', 'Kentucky', 'Louisville'),
  ('Estados Unidos', 'Kentucky', 'Lexington'),
  ('Estados Unidos', 'Kentucky', 'Bowling Green'),
  ('Estados Unidos', 'Louisiana', 'New Orleans'),
  ('Estados Unidos', 'Louisiana', 'Baton Rouge'),
  ('Estados Unidos', 'Louisiana', 'Shreveport'),
  ('Estados Unidos', 'Maine', 'Portland'),
  ('Estados Unidos', 'Maine', 'Lewiston'),
  ('Estados Unidos', 'Maine', 'Bangor'),
  ('Estados Unidos', 'Maryland', 'Baltimore'),
  ('Estados Unidos', 'Maryland', 'Frederick'),
  ('Estados Unidos', 'Maryland', 'Rockville'),
  ('Estados Unidos', 'Massachusetts', 'Boston'),
  ('Estados Unidos', 'Massachusetts', 'Worcester'),
  ('Estados Unidos', 'Massachusetts', 'Springfield'),
  ('Estados Unidos', 'Massachusetts', 'Cambridge'),
  ('Estados Unidos', 'Michigan', 'Detroit'),
  ('Estados Unidos', 'Michigan', 'Grand Rapids'),
  ('Estados Unidos', 'Michigan', 'Warren'),
  ('Estados Unidos', 'Michigan', 'Sterling Heights'),
  ('Estados Unidos', 'Minnesota', 'Minneapolis'),
  ('Estados Unidos', 'Minnesota', 'Saint Paul'),
  ('Estados Unidos', 'Minnesota', 'Rochester'),
  ('Estados Unidos', 'Mississippi', 'Jackson'),
  ('Estados Unidos', 'Mississippi', 'Gulfport'),
  ('Estados Unidos', 'Mississippi', 'Southaven'),
  ('Estados Unidos', 'Missouri', 'Kansas City'),
  ('Estados Unidos', 'Missouri', 'Saint Louis'),
  ('Estados Unidos', 'Missouri', 'Springfield'),
  ('Estados Unidos', 'Montana', 'Billings'),
  ('Estados Unidos', 'Montana', 'Missoula'),
  ('Estados Unidos', 'Montana', 'Great Falls'),
  ('Estados Unidos', 'Nebraska', 'Omaha'),
  ('Estados Unidos', 'Nebraska', 'Lincoln'),
  ('Estados Unidos', 'Nebraska', 'Bellevue'),
  ('Estados Unidos', 'Nevada', 'Las Vegas'),
  ('Estados Unidos', 'Nevada', 'Henderson'),
  ('Estados Unidos', 'Nevada', 'Reno'),
  ('Estados Unidos', 'New Hampshire', 'Manchester'),
  ('Estados Unidos', 'New Hampshire', 'Nashua'),
  ('Estados Unidos', 'New Hampshire', 'Concord'),
  ('Estados Unidos', 'New Jersey', 'Newark'),
  ('Estados Unidos', 'New Jersey', 'Jersey City'),
  ('Estados Unidos', 'New Jersey', 'Paterson'),
  ('Estados Unidos', 'New Jersey', 'Trenton'),
  ('Estados Unidos', 'New Mexico', 'Albuquerque'),
  ('Estados Unidos', 'New Mexico', 'Las Cruces'),
  ('Estados Unidos', 'New Mexico', 'Rio Rancho'),
  ('Estados Unidos', 'New York', 'New York City'),
  ('Estados Unidos', 'New York', 'Buffalo'),
  ('Estados Unidos', 'New York', 'Rochester'),
  ('Estados Unidos', 'New York', 'Yonkers'),
  ('Estados Unidos', 'New York', 'Syracuse'),
  ('Estados Unidos', 'North Carolina', 'Charlotte'),
  ('Estados Unidos', 'North Carolina', 'Raleigh'),
  ('Estados Unidos', 'North Carolina', 'Greensboro'),
  ('Estados Unidos', 'North Carolina', 'Durham'),
  ('Estados Unidos', 'North Dakota', 'Fargo'),
  ('Estados Unidos', 'North Dakota', 'Bismarck'),
  ('Estados Unidos', 'North Dakota', 'Grand Forks'),
  ('Estados Unidos', 'Ohio', 'Columbus'),
  ('Estados Unidos', 'Ohio', 'Cleveland'),
  ('Estados Unidos', 'Ohio', 'Cincinnati'),
  ('Estados Unidos', 'Ohio', 'Toledo'),
  ('Estados Unidos', 'Oklahoma', 'Oklahoma City'),
  ('Estados Unidos', 'Oklahoma', 'Tulsa'),
  ('Estados Unidos', 'Oklahoma', 'Norman'),
  ('Estados Unidos', 'Oregon', 'Portland'),
  ('Estados Unidos', 'Oregon', 'Salem'),
  ('Estados Unidos', 'Oregon', 'Eugene'),
  ('Estados Unidos', 'Pennsylvania', 'Philadelphia'),
  ('Estados Unidos', 'Pennsylvania', 'Pittsburgh'),
  ('Estados Unidos', 'Pennsylvania', 'Allentown'),
  ('Estados Unidos', 'Pennsylvania', 'Erie'),
  ('Estados Unidos', 'Rhode Island', 'Providence'),
  ('Estados Unidos', 'Rhode Island', 'Warwick'),
  ('Estados Unidos', 'Rhode Island', 'Cranston'),
  ('Estados Unidos', 'South Carolina', 'Columbia'),
  ('Estados Unidos', 'South Carolina', 'Charleston'),
  ('Estados Unidos', 'South Carolina', 'Greenville'),
  ('Estados Unidos', 'South Dakota', 'Sioux Falls'),
  ('Estados Unidos', 'South Dakota', 'Rapid City'),
  ('Estados Unidos', 'South Dakota', 'Aberdeen'),
  ('Estados Unidos', 'Tennessee', 'Nashville'),
  ('Estados Unidos', 'Tennessee', 'Memphis'),
  ('Estados Unidos', 'Tennessee', 'Knoxville'),
  ('Estados Unidos', 'Tennessee', 'Chattanooga'),
  ('Estados Unidos', 'Texas', 'Houston'),
  ('Estados Unidos', 'Texas', 'San Antonio'),
  ('Estados Unidos', 'Texas', 'Dallas'),
  ('Estados Unidos', 'Texas', 'Austin'),
  ('Estados Unidos', 'Texas', 'Fort Worth'),
  ('Estados Unidos', 'Texas', 'El Paso'),
  ('Estados Unidos', 'Texas', 'Arlington'),
  ('Estados Unidos', 'Utah', 'Salt Lake City'),
  ('Estados Unidos', 'Utah', 'West Valley City'),
  ('Estados Unidos', 'Utah', 'Provo'),
  ('Estados Unidos', 'Vermont', 'Burlington'),
  ('Estados Unidos', 'Vermont', 'South Burlington'),
  ('Estados Unidos', 'Vermont', 'Rutland'),
  ('Estados Unidos', 'Virginia', 'Virginia Beach'),
  ('Estados Unidos', 'Virginia', 'Norfolk'),
  ('Estados Unidos', 'Virginia', 'Chesapeake'),
  ('Estados Unidos', 'Virginia', 'Richmond'),
  ('Estados Unidos', 'Washington', 'Seattle'),
  ('Estados Unidos', 'Washington', 'Spokane'),
  ('Estados Unidos', 'Washington', 'Tacoma'),
  ('Estados Unidos', 'Washington', 'Vancouver'),
  ('Estados Unidos', 'West Virginia', 'Charleston'),
  ('Estados Unidos', 'West Virginia', 'Huntington'),
  ('Estados Unidos', 'West Virginia', 'Morgantown'),
  ('Estados Unidos', 'Wisconsin', 'Milwaukee'),
  ('Estados Unidos', 'Wisconsin', 'Madison'),
  ('Estados Unidos', 'Wisconsin', 'Green Bay'),
  ('Estados Unidos', 'Wyoming', 'Cheyenne'),
  ('Estados Unidos', 'Wyoming', 'Casper'),
  ('Estados Unidos', 'Wyoming', 'Laramie')
) AS v(pais, region, ciudad)
JOIN paises p ON p.nombre = v.pais
JOIN regiones r ON r.pais_id = p.id AND r.nombre = v.region;

-- ---------- CATEGORÍAS DE PROVEEDOR ----------
INSERT INTO categorias_proveedor (nombre) VALUES
  ('Producción audiovisual'),
  ('Escenografía y montaje'),
  ('Iluminación y sonido'),
  ('Producción técnica (rigging, generadores, carpas)'),
  ('Catering y F&B'),
  ('Logística y transporte'),
  ('Tecnología e interactividad'),
  ('Entretenimiento y artistas'),
  ('Fotografía y video'),
  ('Impresos y señalética'),
  ('Seguridad y protocolo'),
  ('Mobiliario y decoración'),
  ('Gastro bar'),
  ('Hotel'),
  ('Restaurante'),
  ('Rooftop'),
  ('Salón de eventos'),
  ('Club / Discoteca'),
  ('Terraza'),
  ('Finca / Hacienda'),
  ('Merchandising y regalos corporativos'),
  ('Personal BTL (impulsadoras, edecanes, meseros)'),
  ('Permisología y trámites'),
  ('Diseño gráfico y creatividad'),
  ('Flores y ambientación'),
  ('Otro');

-- ---------- FASES DE PROYECTO ----------
-- (quinta revisión: separadas de estados_proyecto para eliminar
-- una dependencia transitiva — ver nota 13 de nexus_schema_v2.sql)
INSERT INTO fases_proyecto (fase, nombre) VALUES
  (1, 'Planeación interna'),
  (2, 'Con decisión del cliente'),
  (3, 'Cierre y facturación');

-- ---------- ESTADOS DE PROYECTO ----------
INSERT INTO estados_proyecto (nombre, fase, orden) VALUES
  ('Planeación interna', 1, 1),
  ('Confirmado', 2, 2),
  ('Planeación', 2, 3),
  ('En curso', 2, 4),
  ('Finalizado', 2, 5),
  ('Cancelado', 2, 6),
  ('No ejecutado', 2, 7),
  ('Ejecutado, pendiente facturar', 3, 8),
  ('Facturado', 3, 9);

-- ---------- DOMINIOS DE CORREO PERMITIDOS (novena revisión; confirmado 2026-08-23) ----------
-- 'agencianextmkt.com' es el ÚNICO dominio permitido para iniciar sesión en el sistema --
-- confirmado explícitamente por la usuaria, con ejemplos reales de cuentas bajo ese dominio
-- (analistacompras@agencianextmkt.com, yuliana.navarro@agencianextmkt.com). La cuenta de Gmail
-- (analistacompras.nexit@gmail.com) que se usa para el envío de correos NO es una cuenta que vaya
-- a iniciar sesión en el sistema -- es solo la que administra el SMTP, por eso su dominio no está
-- ni debe estar en esta lista.
-- 'nextexperiencial.com' se retiró en esta revisión: era un dominio sin confirmar (placeholder del
-- prototipo HTML), y la usuaria ya confirmó que el único dominio de login es 'agencianextmkt.com'.
-- Si más adelante hace falta agregar otro dominio, es un INSERT nuevo en esta misma tabla -- no
-- requiere cambios de código, la validación (trigger + FluentValidation) ya lee esta tabla en vivo.
INSERT INTO dominios_correo_permitidos (dominio) VALUES
  ('agencianextmkt.com');
